# Host: 192.168.3.3  (Version: 5.5.5-10.4.8-MariaDB)
# Date: 2020-05-27 10:25:12
# Generator: MySQL-Front 5.3  (Build 2.77)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

DROP DATABASE IF EXISTS `bdpaulo`;
CREATE DATABASE `bdpaulo` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `bdpaulo`;

#
# Source for table "arxius"
#

DROP TABLE IF EXISTS `arxius`;
CREATE TABLE `arxius` (
  `id` int(11) NOT NULL,
  `idClient` int(11) NOT NULL,
  `idJoc` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idClient` (`idClient`),
  KEY `idJoc` (`idJoc`),
  CONSTRAINT `arxius_ibfk_1` FOREIGN KEY (`idClient`) REFERENCES `clients` (`Id`),
  CONSTRAINT `arxius_ibfk_2` FOREIGN KEY (`idJoc`) REFERENCES `jocs` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# Data for table "arxius"
#

INSERT INTO `arxius` VALUES (1,1,1),(2,1,2),(3,2,1);

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
